### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'includes')`

### ISSUE THREAD

**Issue by MarekSyk** [KyberNetwork/kyberswap-interface#1303]
## URL

https://kyberswap.com/swap

## Error

```
TypeError: Cannot read properties of undefined (reading 'includes')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'includes')
    at rj (https://kyberswap.com/static/js/main.490992f8.chunk.js:1:5379513)
    at Oa (https://kyberswap.com/static/js/main.490992f8.chunk.js:1:2830876)
    at Ts (https://kyberswap.com/static/js/main.490992f8.chunk.js:1:2842564)
    at xc (https://kyberswap.com/static/js/main.490992f8.chunk.js:1:2888999)
    at gu (https://kyberswap.com/static/js/main.490992f8.chunk.js:1:2877052)
    at yu (https://kyberswap.com/static/js/main.490992f8.chunk.js:1:2876980)
    at bu (https://kyberswap.com/static/js/main.490992f8.chunk.js:1:2876843)
    at ou (https://kyberswap.com/static/js/main.490992f8.chunk.js:1:2873623)
    at iu (https://kyberswap.com/static/js/main.490992f8.chunk.js:1:2872174)
    at w (https://kyberswap.com/static/js/main.490992f8.chunk.js:1:3369354)
    at A (https://kyberswap.com/static/js/main.490992f8.chunk.js:1:3369888)
    at chrome-extension://ibnejdfjmmkpcnlpebklmnkoeoihofec/dist/pageHook.js:22:13552
    at p (chrome-extension://ibnejdfjmmkpcnlpebklmnkoeoihofec/dist/pageHook.js:22:13667)
    at s (chrome-extension://ibnejdfjmmkpcnlpebklmnkoeoihofec/dist/pageHook.js:22:13025)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "104.0.5112.102",
    "major": "104"
  },
  "engine": {
    "name": "Blink",
    "version": "104.0.5112.102"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by viet-nv** [comment]
Duplicated with #1297. Fixed in #1299 
Thank for reporting, we will release it soon
