### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'length')`

### ISSUE THREAD

**Issue by Mr-DeMonX** [KyberNetwork/kyberswap-interface#1339]
## URL

https://kyberswap.com/farms?tab=ended

## Error

```
TypeError: Cannot read properties of undefined (reading 'length')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'length')
    at Nn (https://kyberswap.com/static/js/yield-page.3c8134c5.chunk.js:1:119382)
    at Oa (https://kyberswap.com/static/js/main.58c971d7.chunk.js:1:2793763)
    at xc (https://kyberswap.com/static/js/main.58c971d7.chunk.js:1:2851003)
    at gu (https://kyberswap.com/static/js/main.58c971d7.chunk.js:1:2839939)
    at yu (https://kyberswap.com/static/js/main.58c971d7.chunk.js:1:2839867)
    at bu (https://kyberswap.com/static/js/main.58c971d7.chunk.js:1:2839730)
    at ou (https://kyberswap.com/static/js/main.58c971d7.chunk.js:1:2836510)
    at iu (https://kyberswap.com/static/js/main.58c971d7.chunk.js:1:2835061)
    at w (https://kyberswap.com/static/js/main.58c971d7.chunk.js:1:3340279)
    at A (https://kyberswap.com/static/js/main.58c971d7.chunk.js:1:3340813)
    at chrome-extension://ibnejdfjmmkpcnlpebklmnkoeoihofec/dist/pageHook.js:22:13552
    at p (chrome-extension://ibnejdfjmmkpcnlpebklmnkoeoihofec/dist/pageHook.js:22:13667)
    at s (chrome-extension://ibnejdfjmmkpcnlpebklmnkoeoihofec/dist/pageHook.js:22:13025)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "105.0.0.0",
    "major": "105"
  },
  "engine": {
    "name": "Blink",
    "version": "105.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by Mr-DeMonX** [comment]
unable to access Farm and the staked LP

**Comment by namgold** [comment]
Please access by https://kyberswap.com/farms?type=ended
