### ISSUE TITLE
Crash report: `ChunkLoadError: Loading chunk 8 failed.(error: https://app.zeus-swap.network/static/js/elastic-remove-liquidity-page.f9e9a8d5.chunk.js)`

### ISSUE THREAD

**Issue by Jymshelia** [KyberNetwork/kyberswap-interface#1623]
## URL

https://app.zeus-swap.network/elastic/remove/41923

## Error

```
ChunkLoadError: Loading chunk 8 failed.
(error: https://app.zeus-swap.network/static/js/elastic-remove-liquidity-page.f9e9a8d5.chunk.js)
```

## Stacktrace

```
ChunkLoadError: Loading chunk 8 failed.
(error: https://app.zeus-swap.network/static/js/elastic-remove-liquidity-page.f9e9a8d5.chunk.js)
    at i.e (https://app.zeus-swap.network/swap:10:4463)
    at https://app.zeus-swap.network/static/js/main.b3dbb924.chunk.js:2:4839208
    at M (https://app.zeus-swap.network/static/js/main.b3dbb924.chunk.js:2:2960281)
    at Xo (https://app.zeus-swap.network/static/js/main.b3dbb924.chunk.js:2:2738128)
    at e (https://app.zeus-swap.network/static/js/main.b3dbb924.chunk.js:2:2742363)
    at ws (https://app.zeus-swap.network/static/js/main.b3dbb924.chunk.js:2:2754715)
    at xu (https://app.zeus-swap.network/static/js/main.b3dbb924.chunk.js:2:2805080)
    at gc (https://app.zeus-swap.network/static/js/main.b3dbb924.chunk.js:2:2790862)
    at yc (https://app.zeus-swap.network/static/js/main.b3dbb924.chunk.js:2:2790790)
    at bc (https://app.zeus-swap.network/static/js/main.b3dbb924.chunk.js:2:2790653)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "108.0.0.0",
    "major": "108"
  },
  "engine": {
    "name": "Blink",
    "version": "108.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by viet-nv** [comment]
this usually happen when a new version was release and user didn't refresh the page
