### ISSUE TITLE
Crash report: `RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by AguHDz** [KyberNetwork/kyberswap-interface#1749]
## URL

https://kyberswap.com/add/0x3F56e0c36d275367b8C502090EDF38289b3dEa0d/0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8/0x6a4d5f8385ff6e7fc4ebf6f726e12a958daa1cba

## Error

```
RangeError: Maximum call stack size exceeded
```

## Stacktrace

```
RangeError: Maximum call stack size exceeded
    at e.hasOwnProperty (<anonymous>)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765454)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "110.0.0.0",
    "major": "110"
  },
  "engine": {
    "name": "Blink",
    "version": "110.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by viet-nv** [comment]
we fixed this in #1763
