### ISSUE TITLE
Crash report: `RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by guilleup** [KyberNetwork/kyberswap-interface#1750]
## URL

https://kyberswap.com/remove/0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174/0xa3Fa99A148fA48D14Ed51d610c367C61876997F1/0x8eed28c5353987b9e679899c2a047434e600dced

## Error

```
RangeError: Maximum call stack size exceeded
```

## Stacktrace

```
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765351)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
    at e (https://kyberswap.com/static/js/main.72e30d19.chunk.js:1:1765538)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "110.0.0.0",
    "major": "110"
  },
  "engine": {
    "name": "Blink",
    "version": "110.0.0.0"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by viet-nv** [comment]
Duplicated with #1749
