### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by Ivestr** [KyberNetwork/kyberswap-interface#1842]
## URL

https://kyberswap.com/bridge

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at i (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:3191162)
    at r.toFixed (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:578599)
    at at (https://kyberswap.com/static/js/bridge-page.7a11fe7f.chunk.js:1:39398)
    at Oo (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:2454647)
    at Cs (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:2466335)
    at xc (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:2512770)
    at gu (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:2500823)
    at yu (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:2500751)
    at bu (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:2500614)
    at au (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:2497394)
    at iu (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:2495945)
    at j (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:2992464)
    at S (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:2992998)
    at https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:3002612
    at l (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:3002727)
    at n (https://kyberswap.com/static/js/main.3a09af24.chunk.js:1:3001672)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "111.0.0.0",
    "major": "111"
  },
  "engine": {
    "name": "Blink",
    "version": "111.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by Ivestr** [comment]
an error occurs when trying to exchange between Poligon and CRONOS bridges
