### ISSUE TITLE
Crash report: `SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///C:/swap/ethereum' cannot be created in a document with origin 'null' and URL 'file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/swap/ethereum63d2.html'.`

### ISSUE THREAD

**Issue by assinehrd** [KyberNetwork/kyberswap-interface#1848]
## URL

file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/swap/ethereum63d2.html

## Error

```
SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///C:/swap/ethereum' cannot be created in a document with origin 'null' and URL 'file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/swap/ethereum63d2.html'.
```

## Stacktrace

```
Error: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///C:/swap/ethereum' cannot be created in a document with origin 'null' and URL 'file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/swap/ethereum63d2.html'.
    at History.<anonymous> (file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:1420764)
    at m.<computed> [as replaceState] (https://www.googletagmanager.com/gtm.js?id=GTM-TRQCJ8F&gtm_auth=&gtm_preview=&gtm_cookies_win=x:275:435)
    at replace (file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:1323830)
    at file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:2633980
    at file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:2637497
    at rc (file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:2485185)
    at ju (file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:2505412)
    at file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:2502002
    at j (file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:2992464)
    at S (file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:2992998)
    at file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:3002612
    at l (file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:3002727)
    at n (file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/static/js/main.5d95f0de.chunk.js:1:3001672)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "111.0.0.0",
    "major": "111"
  },
  "engine": {
    "name": "Blink",
    "version": "111.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by viet-nv** [comment]
wrong url `file:///C:/Users/ACHOUR/Desktop/kokk/ky/kyberswap.com/swap/ethereum63d2.html` 
Please using kyberswap.com
