### ISSUE TITLE
Crash report: `Error: Invalid address: 1000`

### ISSUE THREAD

**Issue by Hicham44** [KyberNetwork/kyberswap-interface#2470]
## URL

https://kyberswap.com/ethereum/add/0x808507121B80c02388fAd14726482e061B8da827/ETH/1000

## Error

```
Error: Invalid address: 1000
```

## Stacktrace

```
Error: Invalid address: 1000
    at toCallKey (https://kyberswap.com/assets/index-0906b228.js:534:157575)
    at Array.map (<anonymous>)
    at https://kyberswap.com/assets/index-0906b228.js:534:159127
    at Object.useMemo (https://kyberswap.com/assets/index-0906b228.js:36:29469)
    at react_production_min.useMemo (https://kyberswap.com/assets/index-0906b228.js:6:45699)
    at useCallsData (https://kyberswap.com/assets/index-0906b228.js:534:159020)
    at useMultipleContractSingleData (https://kyberswap.com/assets/index-0906b228.js:534:161505)
    at usePairsByAddress (https://kyberswap.com/assets/index-0906b228.js:535:41152)
    at usePairByAddress (https://kyberswap.com/assets/index-0906b228.js:535:42427)
    at Ct (https://kyberswap.com/assets/hooks-8c715455.js:47:3604)
    at _i (https://kyberswap.com/assets/index-98479acf.js:1:24147)
    at li$1 (https://kyberswap.com/assets/index-0906b228.js:36:22270)
    at Hj (https://kyberswap.com/assets/index-0906b228.js:38:3548)
    at Jl (https://kyberswap.com/assets/index-0906b228.js:38:55440)
    at Il (https://kyberswap.com/assets/index-0906b228.js:38:48443)
    at Hl$1 (https://kyberswap.com/assets/index-0906b228.js:38:48254)
    at vl (https://kyberswap.com/assets/index-0906b228.js:38:48084)
    at Al$1 (https://kyberswap.com/assets/index-0906b228.js:38:43588)
    at tl$1 (https://kyberswap.com/assets/index-0906b228.js:38:42388)
    at so (https://kyberswap.com/assets/index-0906b228.js:31:68340)
    at go (https://kyberswap.com/assets/index-0906b228.js:31:68752)
    at https://cdn.segment.com/next-integrations/integrations/vendor/commons.c42222c4cb2f8913500f.js.gz:1:36643
    at y (https://cdn.segment.com/next-integrations/integrations/vendor/commons.c42222c4cb2f8913500f.js.gz:1:36758)
    at c (https://cdn.segment.com/next-integrations/integrations/vendor/commons.c42222c4cb2f8913500f.js.gz:1:36116)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
  "browser": {
    "name": "Brave",
    "version": "121.0.0.0",
    "major": "121"
  },
  "engine": {
    "name": "Blink",
    "version": "121.0.0.0"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {
    "vendor": "Apple",
    "model": "Macintosh"
  },
  "cpu": {}
}
```

**Comment by viet-nv** [comment]
Protocols (Elastic, Classic) are not supported since 03/2024
